services:

  nginx-web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-web
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
    ports:
      - "80:80"
    volumes:
      - web_content:/usr/share/nginx/html
    networks:
      infra_red:
        ipv4_address: 172.20.0.10
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: seguro123
      POSTGRES_DB: practica10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./postgres/backup_postgres.sh:/usr/local/bin/backup_postgres.sh
    networks:
      infra_red:
        ipv4_address: 172.20.0.20

  ftp-server:
    build:
      context: ./ftp
      dockerfile: Dockerfile
    container_name: ftp-server
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    mem_limit: 256m
    cpus: "0.25"
    ports:
      - "21:21"
      - "21100-21105:21100-21105"
    volumes:
      - web_content:/ftp/webfiles
    networks:
      infra_red:
        ipv4_address: 172.20.0.30

volumes:
  db_data:
    name: db_data
  web_content:
    name: web_content

networks:
  infra_red:
    name: infra_red
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
