local_enable=YES
write_enable=YES
anonymous_enable=NO
chroot_local_user=YES
allow_writeable_chroot=YES
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21105
pasv_address=127.0.0.1
xferlog_enable=YES
local_umask=022
listen=YES
listen_ipv6=NO
listen_port=21
local_root=/ftp/webfiles
seccomp_sandbox=NO
